name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Autenticarse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y etiquetar la imagen Docker
      - name: Build and tag Docker image
        run: |
          docker build -t matiasfontecilla/taller3:latest .
          docker tag matiasfontecilla/taller3:latest matiasfontecilla/taller3:${{ github.sha }}

      # 5taller3 Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push matiasfontecilla/taller3:latest
          docker push matiasfontecilla/taller3:${{ github.sha }}
